# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
site_name: Gluten

repo_name: 'Fork on GitHub '
repo_url: "https://github.com/apache/gluten.git"
edit_uri: ""


nav:
- Home: index.md
- Getting Started:
  - get-started/getting-started.md
  - Velox Backend: get-started/Velox.md
  - ClickHouse Backend: get-started/ClickHouse.md
  - Build Guide: get-started/build-guide.md
  - Gluten UI: get-started/GlutenUI.md
  - Velox with S3: get-started/VeloxS3.md
  - Velox with ABFS: get-started/VeloxABFS.md
  - Velox with GCS: get-started/VeloxGCS.md
  - Velox with Delta Lake: get-started/VeloxDelta.md
  - Velox with Iceberg: get-started/VeloxIceberg.md
  - Velox with GPU: get-started/VeloxGPU.md
  - Velox with QAT: get-started/VeloxQAT.md
  - Velox Local Caching: get-started/VeloxLocalCache.md
  - Stage Resource Adjustment: get-started/VeloxStageResourceAdj.md
- Configuration:
  - Gluten Configuration: Configuration.md
  - Velox Configuration: velox-configuration.md
  - Spark Configuration: velox-spark-configuration.md
  - Parquet Write Configuration: velox-parquet-write-configuration.md
- Velox Backend Reference:
  - Support Progress: velox-backend-support-progress.md
  - Limitations: velox-backend-limitations.md
  - Scalar Functions: velox-backend-scalar-function-support.md
  - Aggregate Functions: velox-backend-aggregate-function-support.md
  - Window Functions: velox-backend-window-function-support.md
  - Generator Functions: velox-backend-generator-function-support.md
  - Troubleshooting: velox-backend-troubleshooting.md
- Developers:
  - Overview: developers/README.md
  - New to Gluten: developers/NewToGluten.md
  - How To: developers/HowTo.md
  - How to Release: developers/HowToRelease.md
  - C++ Coding Style: developers/CppCodingStyle.md
  - Substrait Modifications: developers/SubstraitModifications.md
  - Micro Benchmarks: developers/MicroBenchmarks.md
  - Velox UDF and UDAF: developers/VeloxUDF.md
  - Velox Function Development: developers/velox-function-development-guide.md
  - Velox Backend CI: developers/velox-backend-CI.md
  - Build in Docker: developers/velox-backend-build-in-docker.md
  - Query Trace: developers/QueryTrace.md
  - Memory Profiling: developers/ProfileMemoryOfGlutenWithVelox.md
  - Dynamic Off-Heap Sizing: developers/VeloxDynamicSizingOffheap.md
  - Partial Project: developers/PartialProject.md
  - Bloop Integration: developers/bloop-integration.md
  - Debug CH Backend: developers/clickhouse-backend-debug.md
  - Jemalloc with CH: developers/UsingJemallocWithCH.md
  - Gperftools with CH: developers/UsingGperftoolsInCH.md
  - Improvement Proposals: developers/improvement-proposals.md



theme: readthedocs


plugins:
  - search
  - mkdocs-versioning:
      version: 1.2.0
      exclude_from_nav: ["image", "js", "css", "fonts", "img"]
