# sonar.login=$(cat /tmp/sonarqube-token)
sonar.host.url=$SONAR_HOST_URL
sonar.working.directory=$SONAR_DIR
sonar.settings=${WORKSPACE}/.m2/settings.xml
sonar.security.settings=${WORKSPACE}/.m2/settings_security.xml
sonar.projectKey=412037-1686233
sonar.java.binaries="${WORKSPACE}/target"
sonar.projectName=lakehouse/gluten
sonar.sources=.
sonar.projectVersion=27243
sonar.exclusions=**/**Test.java
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true